# Generated by Django 3.2.9 on 2021-12-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
