# Generated by Django 3.2.9 on 2021-12-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_core', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='replie',
            name='image',
        ),
    ]
