# Generated by Django 3.2.9 on 2021-12-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_core', '0003_auto_20211228_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='replie',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
